export const speciesCategories = [
  'sponges',
  'staghorn, elkhorn and finger corals',
  'cardinalfishes',
  'tube, branch and leaf corals',
  'jellyfish',
  'barracudas',
  'tunicates, sea stars, worms and anemones',
  'soft corals',
  'octopus and squid',
  'dragonets',
  'porcupinefishes',
  'blenny',
  'burrfish',
  'surgeonfishes',
  'slim-bodied fishes',
  'gobies',
  'groupers',
  'parrotfishes',
  'eels',
  'pufferfishes',
  'snapper',
  'boxfishes',
  'angelfishes',
  'spadefish',
  'butterflyfishes',
  'bigeyes',
  'squirrelfishes',
  'rays',
  'wrasses',
  'damselfishes',
  'drums',
  'crustaceans',
  'sharks commenseals',
  'goatfishes',
  'triggerfishes',
  'grunts',
  'seabasses and basslets',
  'filefishes',
  'lionfises and scorpionfishes and rockfishes',
  'jacks',
  'flatfish',
  'other',
  'sharks',
];
