export const buttons = [
  {
    connectedMode: 'recent',
    text: 'Recent',
  },
  {
    connectedMode: 'oldest',
    text: 'Oldest',
  },
  {
    connectedMode: 'drafts',
    text: 'Drafts',
  },
];

export const DUMMY_DATA = [
  {
    id: 1,
    number: 1,
    date: 'September 15, 2021',
    spot: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 138,
    number: 138,
    date: 'August 8, 2020',
    spot: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 15,
    number: 15,
    date: 'January 31, 2021',
    spot: 'Spooky Channel, Honduras, Roatan West End',
    divetime: 120,
    depth: 12,
    diversCount: 5,
    trip: 'Honduras, 2022',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 14,
    number: 14,
    date: 'September 15, 2015',
    spot: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 18,
    number: 18,
    date: 'August 8, 2020',
    spot: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 150,
    number: 150,
    date: 'September 15, 2015',
    spot: 'Spooky Channel, Honduras, Roatan West End',
    divetime: 120,
    depth: 12,
    diversCount: 5,
    trip: 'Honduras, 2022',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 71,
    number: 71,
    date: 'August 8, 2020',
    spot: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 178,
    number: 178,
    date: 'September 15, 2015',
    spot: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 105,
    number: 105,
    date: 'August 8, 2020',
    spot: 'Spooky Channel, Honduras, Roatan West End',
    divetime: 120,
    depth: 12,
    diversCount: 5,
    trip: 'Honduras, 2022',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 151,
    number: 151,
    date: 'September 15, 2015',
    spot: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 171,
    number: 171,
    date: 'September 15, 2015',
    spot: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
];
