import React from 'react';
import { Delete } from '../Icons/IconSVGComponents/Delete';
import { EditDive } from '../Icons/IconSVGComponents/Editdive';
import { Export } from '../Icons/IconSVGComponents/Export';
import { Paste } from '../Icons/IconSVGComponents/Paste';
import { Print } from '../Icons/IconSVGComponents/Print';
import { Unpublish } from '../Icons/IconSVGComponents/Unpublish';
import { CopyProperty } from '../Icons/IconSVGComponents/CopyProperty';
import pageRoutes from '../../routes/pagesRoutes.json';

export const dropdownList = [
  {
    id: 1,
    title: 'Print',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <Print />,
  },
  {
    id: 2,
    title: 'Export',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <Export />,
  },
  {
    id: 3,
    title: 'Edit Dive',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <EditDive />,
  },
  {
    id: 4,
    title: 'Copy Property',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <CopyProperty />,
  },
  {
    id: 5,
    title: 'Paste properties',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <Paste />,
  },
  {
    id: 6,
    title: 'Unpublish',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <Unpublish />,
  },
  {
    id: 7,
    title: 'Delete',
    link: pageRoutes.diveManagerPageRout,
    svgItem: <Delete />,
  },
];

export const buttons = [
  {
    connectedMode: 'recent',
    text: 'Recent',
  },
  {
    connectedMode: 'oldest',
    text: 'Oldest',
  },
  {
    connectedMode: 'drafts',
    text: 'Drafts',
  },
];

export const DUMMY_DATA = [
  {
    id: 1,
    number: 1,
    date: 'September 15, 2021',
    divedPlace: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 138,
    number: 138,
    date: 'August 8, 2020',
    divedPlace: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 15,
    number: 15,
    date: 'January 31, 2021',
    divedPlace: 'Spooky Channel, Honduras, Roatan West End',
    divetime: 120,
    depth: 12,
    diversCount: 5,
    trip: 'Honduras, 2022',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 14,
    number: 14,
    date: 'September 15, 2015',
    divedPlace: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 18,
    number: 18,
    date: 'August 8, 2020',
    divedPlace: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 150,
    number: 150,
    date: 'September 15, 2015',
    divedPlace: 'Spooky Channel, Honduras, Roatan West End',
    divetime: 120,
    depth: 12,
    diversCount: 5,
    trip: 'Honduras, 2022',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 71,
    number: 71,
    date: 'August 8, 2020',
    divedPlace: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 178,
    number: 178,
    date: 'September 15, 2015',
    divedPlace: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 105,
    number: 105,
    date: 'August 8, 2020',
    divedPlace: 'Spooky Channel, Honduras, Roatan West End',
    divetime: 120,
    depth: 12,
    diversCount: 5,
    trip: 'Honduras, 2022',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 151,
    number: 151,
    date: 'September 15, 2015',
    divedPlace: 'Naama Bay, Egypt, Sharm El Shaikh',
    divetime: 50,
    depth: 10,
    diversCount: 2,
    trip: 'Egypt, 2021',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
  {
    id: 171,
    number: 171,
    date: 'September 15, 2015',
    divedPlace: 'Zenobia Wreck, Cyprus, Larnaca',
    divetime: 35,
    depth: 6,
    diversCount: 10,
    trip: 'Cyprus, 2020',
    diveShop: 'Crest Dive Center',
    water: 'salted',
    visibility: 'good',
    altitude: 1,
    featuredGear: 'Mares Nemo Excel',
  },
];
