export const localSpecies = [
  {
    id: '27s4D0GQ7wffhqoJ1tS6',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: '2eOGu289O8N0Wr6PoyZj',
    oldId: 206322,
    imageSrc: null,
    category: 'others',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: '4tXDwuck3YaurzIv3fkX',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: '51DuLgGWYE8zH09uGed6',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'EjVBUi9oRBC1OmNu8Cpj',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'GQelRDgShuxvHqtEPeRq',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'GootoUR6UHAm6IaAMU7N',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'HaX2fq8QLL1uCDutY5os',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'IbvA027CUprT9loJgOV3',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'JKNZWFDHJBXXY6DtTsb2',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'KhN1NYfLTswMLnzADgZR',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'KijwnLAkKJe6XCPUr0dL',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'LnzVjuqRbGP8vHDqQUZB',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'M3csQcobHTQ5rdaj27DH',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'Myz2HNfLfm56LqHVKGm9',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'N7nUqq9aZDjfQQNIxpFL',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'NwPMtH1PO6humMdVRxk5',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'OkucBlgjAJXKBWUAZdWg',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'PXqF1zNuuudLK3zmPeOX',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'QuVBHYbrdg76aBHV4bIh',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'SGtmbpGxw9kTbk8UPMai',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'WKQb5AguVmsj2Rr7ZD1p',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'ZIGNJMauY1aHXEFIvh4c',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'asK8lDzBgnj5VXbdYw9z',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'avzzjfFpazDVyWTtfzBH',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'bpTl221ixg0XiTrW5Jdq',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'eE1ghhfpHwlqooFkU1im',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'eQNWHxiLGWVddVrN7KBo',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'eVyA4zQnaC9kzA1NHFOn',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'fM8T4iXIPyihdq86Nmfx',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'fYtAj942ttzMyBB161wc',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'ffwy3CCBO9NL7q7RksuE',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'fhhFF1MyDNC6hLcy3cM5',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'lboc3wiXOn349Lpjieax',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'lxeK97PE06CGjoE12GoJ',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'olHaJKNQfNRMpH2xKTNd',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'pqs0BFJk5lge3kaiAQvO',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'qpKcHXaQ0qC5osu4kKm1',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'r0iDluFqhDnrohuVOem9',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 's43rEXz8qYRdIX2pDyKR',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'sRtOs1b43djn4Xgdo0bQ',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'tlcFTMhFmXrx2VA3m84T',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'wqSpw4yxLlkJupkZtqKm',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
  {
    id: 'xHv8jVQiJexWBlARB8Ro',
    oldId: 206322,
    imageSrc: null,
    category: 'drums',
    sname: 'Ophioscion imiceps (Jordan & Gilbert, 1882)',
  },
];

export const speciesCategories = {
  Crustaceans: 15578,
  Sponges: 7683,
  Jellyfish: 3816,
  'Soft Corals': 2990,
  'Lionfises And Scorpionfishes And Rockfishes': 1894,
  Gobies: 1774,
  'Tunicates, Sea Stars, Worms And Anemones': 1575,
  Eels: 1066,
  Blenny: 1030,
  Flatfish: 912,
  Rays: 714,
  Wrasses: 573,
  Sharks: 627,
  'Octopus And Squid': 634,
  'Staghorn, Elkhorn And Finger Corals': 382,
  Damselfishes: 379,
  'Tube, Branch And Leaf Corals': 429,
  Cardinalfishes: 358,
  'Seabasses And Basslets': 374,
  Drums: 349,
  'Slim-Bodied Fishes': 259,
  'Flower, Brain And Pillar Corals': 275,
  Groupers: 220,
  Dragonets: 210,
  Pufferfishes: 213,
  Jacks: 181,
  Grunts: 161,
  Butterflyfishes: 141,
  Porgies: 161,
  Snapper: 130,
  Filefishes: 134,
  Parrotfishes: 108,
  Angelfishes: 100,
  Jawfish: 76,
  Goatfishes: 78,
  Surgeonfishes: 70,
  Triggerfishes: 55,
  Squirrelfishes: 44,
  Boxfishes: 42,
  Hawkfish: 45,
  Clownfishes: 32,
  Sweeper: 29,
  Barracudas: 29,
  Nudibranchs: 585,
  Unicornfishes: 20,
  Bigeyes: 23,
  Spadefish: 24,
  Burrfish: 10,
  'Sharks Commenseals': 16,
  'Sea Turtles': 14,
  Porcupinefishes: 6,
  'Tarpon And Bonefish': 4,
  'Sea Urchins': 54,
  Snook: 0,
};
