export const mySpecies = [
  {
    id: 's-216067',
    sname: 'Gobionellus stomatus Starks, 1913',
    cnames: [
      '\u5927\u53e3\u5c0f\u9c15\u864e\u9c7c',
      '\u5927\u53e3\u5c0f\u9c15\u864e\u9b5a',
      'Amor\u00e9',
      'Peixe-flor',
    ],
    preferred_name: '\u5927\u53e3\u5c0f\u9c15\u864e\u9c7c',
    picture: '',
    bio: '',
    url: 'http://www.eol.org/pages/216067',
    rank: 'species',
  },
  {
    id: 's-216074',
    sname: 'Awaous acritosus Watson, 1994',
    cnames: ['Roman nose goby'],
    preferred_name: 'Roman nose goby',
    picture: 'https://content.eol.org/data/media/2c/e1/bd/18.https___www_inaturalist_org_photos_187390.jpg',
    bio: 'Found in streams and rivers of lowland regions, above tidal influence.  Collected from generally clear waters , over bottoms usually consisting of gravel, sand and some mud.  Feeds mostly on algae  and bottom detritus.  Little is known of the life history, but it probably has a marine larval stage.  Only recently described, although it has long been misidentified as Awaous crassilabrus, a species that does not occur in Australia .',
    url: 'http://www.eol.org/pages/216074',
    rank: 'species',
  },
];

export const speciesListData = {
  gobies: [
    {
      id: 's-23842',
      sname: 'Gobiosoma nudum (Meek & Hildebrand, 1928)',
      cnames: [
        '\u88f8\u9b88\u9c15\u864e\u9b5a',
        '\u88f8\u9b88\u9c15\u864e\u9c7c',
        'goby',
        'Knobchin goby',
        'Gobio',
        'gobio bulto',
      ],
      preferred_name: 'goby',
      picture: 'https://content.eol.org/data/media/2c/e1/bd/18.https___www_inaturalist_org_photos_187390.jpg',
      bio: '',
      url: 'http://www.eol.org/pages/23842',
      rank: 'species',
    },
    {
      id: 's-206252',
      sname: 'Calumia godeffroyi (G\u00fcnther, 1877)',
      cnames: [
        '\u5de7\u5858\u9ce2',
        '\u5de7\u5858\u9c67',
        'Stertgesig-slaper',
        'Tailface sleeper',
      ],
      preferred_name: 'Tailface sleeper',
      picture: 'https://content.eol.org/data/media/2c/e1/bd/18.https___www_inaturalist_org_photos_187390.jpg',
      bio: 'Lives among coral and rubble .',
      url: 'http://www.eol.org/pages/206252',
      rank: 'species',
    },
  ],
  sharks: [
    {
      id: 's-356458',
      sname: 'Elacatinus evelynae (B\u00f6hlke & Robins, 1968)',
      cnames: [
        '\u4f0a\u592b\u6797\u9b88\u9c15\u864e\u9c7c',
        '\u4f0a\u592b\u6797\u9b88\u9c15\u864e\u9b5a',
        'sharknose goby',
        'Shark nose goby',
        'sharpnose goby',
        'Gobio hocicudo',
        'gobio tiburoncito',
      ],
      preferred_name: 'sharknose goby',
      picture: 'http://eol.org/content/2011/05/12/04/07648_medium.jpg',
      bio: 'Inhabits coral reefs with clear waters, preferably in oceanic, insular areas .  In pairs near coral heads.  Monogamous .  A cleaner .  Minimum depth reported from Ref. 27115.  Has been reared in captivity .  Feeds on ectoparasites of fishes .',
      url: 'http://www.eol.org/pages/356458',
      rank: 'species',
    },
    {
      id: 's-356459',
      sname: 'Elacatinus illecebrosus (B\u00f6hlke & Robins, 1968)',
      cnames: [
        '\u8bf1\u60d1\u9b88\u9c15\u864e\u9c7c',
        '\u8a98\u60d1\u9b88\u9c15\u864e\u9b5a',
        'Barsnout goby',
        'gobio seductor',
      ],
      preferred_name: 'Barsnout goby',
      picture: 'https://content.eol.org/data/media/2c/e1/bd/18.https___www_inaturalist_org_photos_187390.jpg',
      bio: 'Found in groups near coral heads.  Monogamous .',
      url: 'http://www.eol.org/pages/356459',
      rank: 'species',
    },
    {
      id: 's-203913',
      sname: 'Trimma flavatrum Hagiwara & Winterbottom, 2007',
      cnames: ['Wasp pygmy goby', 'Hime-aogi-haze'],
      preferred_name: 'Wasp pygmy goby',
      picture: '',
      bio: 'This species forms small schools which are sometimes mixed with T. tevegae.  The fishes hover in caves, recesses or under the overhangs of coral reefs.  When hovering, the ventral side faces the nearest substrate surface  the same as with T. tevegae.  However, T. flavatrum tends to be found more towards the back of the caves and recesses .',
      url: 'http://www.eol.org/pages/203913',
      rank: 'species',
    },
  ],
};
